name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Git Version
      uses: codacy/git-version@2.4.0
      with:
        # The name of the release branch
        release-branch: master
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag heinanca/jenkins-exporter:$(date +%s)
